#!/usr/bin/env bash

if [ ! -d  "/var/www/$DOCUMENT_ROOT" ]; then
  echo "Creating folder /var/www/$DOCUMENT_ROOT"
  mkdir -p "/var/www/$DOCUMENT_ROOT"
else
  echo "/var/www/$DOCUMENT_ROOT already exists."
fi

echo "Setting document root to /var/www/$DOCUMENT_ROOT"

export LISTENPORT=${LISTENPORT:-80}
export SERVER_NAME=${SERVER_NAME:-_}
export DOCUMENT_ROOT=${DOCUMENT_ROOT:-html}
export BACKEND_NAME=${BACKEND_NAME:-127.0.0.1}
export BACKEND_PORT=${BACKEND_PORT:-9000}

envsubst '${LISTENPORT} ${SERVER_NAME} ${DOCUMENT_ROOT} ${BACKEND_NAME} ${BACKEND_PORT}' > /etc/nginx/sites-enabled/site.conf < /etc/nginx/sites-available/site.conf.templ

ln -sf /dev/stdout /var/log/nginx/$SERVER_NAME.access.log
ln -sf /dev/stderr /var/log/nginx/$SERVER_NAME.error.log
